### ISSUE TITLE
LandingAnimator Crash

### ISSUE THREAD

**Issue by eygraber** [wasabeef/recyclerview-animators#15]
I've been getting this crash in my logs ever since adding a LandingAnimator to my app. I'm not sure if this is a problem with RecyclerView or not, but I figured I'd post the stacktrace here, and see what you think about it.

```
java.lang.NullPointerException
       at android.support.v7.widget.OrientationHelper$2.getDecoratedStart(OrientationHelper.java:316)
       at android.support.v7.widget.LinearLayoutManager.findOneVisibleChild(LinearLayoutManager.java:1633)
       at android.support.v7.widget.LinearLayoutManager.findFirstVisibleChildClosestToStart(LinearLayoutManager.java:1453)
       at android.support.v7.widget.LinearLayoutManager.computeScrollOffset(LinearLayoutManager.java:997)
       at android.support.v7.widget.LinearLayoutManager.computeVerticalScrollOffset(LinearLayoutManager.java:969)
       at android.support.v7.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:1175)
       at android.view.View.canScrollVertically(View.java:11991)
       at android.support.v4.view.ViewCompatICS.canScrollVertically(ViewCompatICS.java:35)
       at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(ViewCompat.java:940)
       at android.support.v4.view.ViewCompat.canScrollVertically(ViewCompat.java:1237)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:6594)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:6573)
       at android.support.v7.widget.LinearLayoutManager.onInitializeAccessibilityEvent(LinearLayoutManager.java:204)
       at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:66)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:228)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:56)
       at android.view.View.onInitializeAccessibilityEvent(View.java:5101)
       at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:4974)
       at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:19428)
       at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatIcs.java:117)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:210)
       at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:358)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:255)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatJellyBean.java:82)
       at android.view.View.sendAccessibilityEventUnchecked(View.java:4959)
       at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:6895)
       at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:6923)
       at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:6151)
       at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:6224)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2549)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2549)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2549)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2549)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2549)
       at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:2549)
       at android.view.View.notifySubtreeAccessibilityStateChangedIfNeeded(View.java:7343)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3881)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:3809)
       at android.support.v7.widget.RecyclerView$4.removeViewAt(RecyclerView.java:394)
       at android.support.v7.widget.ChildHelper.removeViewIfHidden(ChildHelper.java:336)
       at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:775)
       at android.support.v7.widget.RecyclerView.access$5300(RecyclerView.java:127)
       at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onChangeFinished(RecyclerView.java:8278)
       at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchChangeFinished(RecyclerView.java:8590)
       at jp.wasabeef.recyclerview.animators.BaseItemAnimator$5.onAnimationEnd(BaseItemAnimator.java:326)
       at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1030)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
       at android.animation.ValueAnimator.cancel(ValueAnimator.java:969)
       at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:412)
       at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(ViewPropertyAnimatorCompatICS.java:102)
       at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(ViewPropertyAnimatorCompat.java:438)
       at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(ViewPropertyAnimatorCompat.java:1001)
       at jp.wasabeef.recyclerview.animators.BaseItemAnimator.endAnimation(BaseItemAnimator.java:397)
       at android.support.v7.widget.RecyclerView$Recycler.getScrapViewForPosition(RecyclerView.java:4035)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3626)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1859)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:356)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1274)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:525)
       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:151)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14946)
       at android.view.ViewGroup.layout(ViewGroup.java:4651)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2132)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1872)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1075)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5878)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5097)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by wasabeef** [comment]
@eygraber 

Hi.

Cause I seems to be separately...

**Comment by eygraber** [comment]
I filed an issue with the Android bug tracker - https://code.google.com/p/android/issues/detail?id=162753
