### ISSUE TITLE
SlideInRightAnimator Crash

### ISSUE THREAD

**Issue by kronenz** [wasabeef/recyclerview-animators#16]
i'm using API 15 on Samsung Galaxy Tab 10.1

call AB method on UiThread  

next .. error message

java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{4142f648 position=6 id=-1, oldPos=-1, pLpos:7undefined adapter position no parent}
            at android.support.v7.widget.RecyclerView$4.attachViewToParent(RecyclerView.java:422)
            at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:208)
            at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:5239)
            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:5216)
            at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:5204)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1325)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1274)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:525)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2072)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11477)
            at android.view.ViewGroup.layout(ViewGroup.java:4232)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1692)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2649)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4507)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by hd132518** [comment]
I get the same error when i call notifyitemrangechanged, notifyitemremoved, etc.

**Comment by wasabeef** [comment]
oh..

What's version?

**Comment by huangjinhong** [comment]
I get the same error when i call notifyitemrangechanged, notifyitemremoved, etc.

me too!

**Comment by wasabeef** [comment]
@huangjinhong 

Cloud you show me code
