### ISSUE TITLE
can not resolve it

### ISSUE THREAD

**Issue by jiangTaoQuite** [wasabeef/recyclerview-animators#61]
I use the package of   "com.android.support:recyclerview-v7:23.1.1",when I was dependencies jp.wasabeef:recyclerview-animators:2.1.0,It declare that  Failed to resolve: jp.wasabeef:recyclerview-animators:2.1.0

**Comment by wasabeef** [comment]
@jiangTaoQuite 

Cloud you show me gradle code

**Comment by jiangTaoQuite** [comment]
I use Android Studio for auto gradle,But I love over log,The result is : 

Caused by: org.gradle.api.internal.MissingMethodException: Could not find method compile() for arguments [jp.wasabeef:recyclerview-animators:2.1.0] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@390e9281.
	at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
	at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated.invokeMethod(Unknown Source)
	at build_bcn6omufmfegv6pqa1masia54$_run_closure1_closure3.doCall(/home/mr-jiang/project/AndroidStudio/LifeTime/build.gradle:9)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
	at org.gradle.api.internal.initialization.DefaultScriptHandler.dependencies(DefaultScriptHandler.java:54)
	at build_bcn6omufmfegv6pqa1masia54$_run_closure1.doCall(/home/mr-jiang/project/AndroidStudio/LifeTime/build.gradle:7)

**Comment by wasabeef** [comment]
@jiangTaoQuite 

Do you add the jcenter?

**Comment by jiangTaoQuite** [comment]
yes

**Comment by markoilicic** [comment]
I'm getting same error for `jp.wasabeef:recyclerview-animators:2.2.1`...
Actually, I get error for all versions after `1.2.0`... I'm using recyclerView version `23.2.1`.. Any idea why this is happening?
