### ISSUE TITLE
java.lang.IndexOutOfBoundsException when removing item animator

### ISSUE THREAD

**Issue by emartynov** [wasabeef/recyclerview-animators#64]
Thank you for the library. 

Recently we got a crash. 
```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
at java.util.ArrayList.remove(ArrayList.java:399)
at jp.wasabeef.recyclerview.animators.BaseItemAnimator.endAnimations(BaseItemAnimator.java:598)
at android.support.v7.widget.RecyclerView.onDetachedFromWindow(RecyclerView.java:2067)
at android.view.View.dispatchDetachedFromWindow(View.java:11972)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2530)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2530)
at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3616)
at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3591)
at android.view.ViewGroup.removeView(ViewGroup.java:3523)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1167)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1345)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:695)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

With this code:
```
public class FirstTimeCardsSlideDownAnimator extends SlideInDownAnimator {

    protected static final int SLIDE_DOWN_ANIMATION_DURATION = 1500;

    private RecyclerView recyclerView;

    public FirstTimeCardsSlideDownAnimator() {
        super(new OvershootInterpolator(1f));
        setAddDuration(SLIDE_DOWN_ANIMATION_DURATION);
    }

    @Override
    public void onAnimationFinished(final RecyclerView.ViewHolder viewHolder) {
        super.onAnimationFinished(viewHolder);
        recyclerView.setItemAnimator(null);

        recyclerView.getAdapter().notifyItemChanged(2);
    }
}
```
It happens when we go to another activity while animation is still going.

**Comment by emartynov** [comment]
Sure thing we are doing something weird. But is there way of having default animation after some period of time or event?

**Comment by wasabeef** [comment]
Hi, @emartynov 

this you need?
`recyclerView.setItemAnimator(null);`

**Comment by emartynov** [comment]
Hi @wasabeef!

The question was if I can remove it? 
Maybe if I find a solution for my requirement:

I need to use different animation for first two cells
After I need to show default animation

I set Animator and trying to remove at the end of the animation. Maybe I can achieve it differently.
